api_id = "20619533"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #)<@scaMmEr<
api_hash = "5893568858a096b7373c1970ba05e296"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               #)sCaMMER^
bot_token = "7723159440:AAEAzl4UvOXBGj2PZF9Q6gabnrk6XCli0-8"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #-=(ScAMMeR>
FORCE_CHANNEL = 'botsupdatesbynaruto'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #@_&ScAMmeR#<+
LOGS_CHANNEL = -1002351215681                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #^ScAmmeR%%*
OWNER = 7447651332                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #$^sCAmMer_
image = 'logo.jpg'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #(SCammER-
MONGO_URI = 'mongodb+srv://lodalesson876:FKxK7BZGq1WzE4ae@cluster0.or1gz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #<##sCAMmer$)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           #<##sCAMmer$)
name = 'saksham'
OWNER_USERNAME = 'Ⓢⓐⓚⓢⓗⓐⓜ Ⓑⓗⓐⓘⓨⓐ'

START_TEXT="""
I'm Batch-Txt Extractor bot....!

🚀 Made By @sakshambhaiya🚀

Usage : First select the app listed below. ⤵️
"""
START_TEXT1="""
I'm Batch-Txt Extractor bot....!

🎯 Made By @sakshambhaiya 🎯
🔰  Now, select the course listed below. 📌
"""
START_TEXTCP="""
I'm CLASSPLUS Extractor bot....!

⤵️  Now, select the Option listed below. 🎯
"""
START_TEXTAPPX="""
I'm APPX Extractor bot....!

🔰  Now, select the Option listed below. 🎯
"""
START_TEXTCP1="""
I'm Going to Generate Auth Token....!

🎯  Now, select the Methods to Geneterate Classplus Auth Token. ✅
"""
HELP_TEXT="""
I'm Batch extractor bot...!
🚀Commands

/helper - For Extracting Txts.

⚠️ Save this id » @sakshambhaiya in case of Copyright infringement.
"""
